server:
  port: 8083
spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/payments
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false

    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  cloud:
    function:
      definition: paymentAcceptedSupplier;paymentRejectedSupplier
    stream:
      bindings:
        paymentAcceptedSupplier-out-0:
          destination: payment.accepted.exchange
          content-type: application/json
          producer:
            durable-expression: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, prometheus
    prometheus:
      enabled: true

resilience4j:
  retry:
    instances:
      orderServiceBackoffRetry:
        maxAttempts: 4
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        exponentialBackoffMaxWait: 5000
        retryExceptions:
          - feign.FeignException

circuitbreaker:
  instances:
    orderServiceCircuitBreaker:
      failureRateThreshold: 50
      waitDurationInOpenState: 30s
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      recordExceptions:
        - feign.FeignException

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: payments
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: payments
      paths-to-match: /payments/**
      packages-to-scan: com.arka.payments
