server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/payments
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  cloud:
    function:
      definition: paymentAcceptedSupplier;paymentRejectedSupplier
    stream:
      bindings:
        paymentAcceptedSupplier-out-0:
          destination: payment.accepted.exchange
          content-type: application/json
          producer:
            durable-expression: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh

resilience4j:
  retry:
    instances:
      orderServiceBackoffRetry:
        maxAttempts: 4
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        exponentialBackoffMaxWait: 5000
        retryExceptions:
          - feign.FeignException

circuitbreaker:
  instances:
    orderServiceCircuitBreaker:
      failureRateThreshold: 50
      waitDurationInOpenState: 30s
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      recordExceptions:
        - feign.FeignException